name: "Build"

on:
  push:
    branches: [main]
    paths-ignore: ["**/*.md"]
  pull_request:
    branches: [main]
    paths-ignore: ["**/*.md"]
  workflow_dispatch:

jobs:
  call:
    uses: jellyfin/jellyfin-meta-plugins/.github/workflows/build.yaml@8eed318e74aed0a7cc41de6dafd36eb693a1f6fc # master
    with: 
      dotnet-target: 'net10.0'
      dotnet-version: '10.0.x'
