name: "Release Drafter & Prep PR"

on:
  push:
    branches: [main]
    paths-ignore: [build.yaml]
  workflow_dispatch:

jobs:
  call:
    permissions:
      contents: write
      pull-requests: read
    uses: jellyfin/jellyfin-meta-plugins/.github/workflows/changelog.yaml@5ebf9f9455736773ab6f94cdb19fb903ece41b83 # master
    with:
      repository-name: DaniCatGames/jellyfin-openid-connect
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
