name: "Release Drafter & Prep PR"

on:
  push:
    branches: [main]
    paths-ignore: [build.yaml]
  workflow_dispatch:

jobs:
  call:
    permissions:
      contents: write
      pull-requests: read
    uses: jellyfin/jellyfin-meta-plugins/.github/workflows/changelog.yaml@91aa56610cd3321f8897bbe2657c1743b3df3436 # master
    with:
      repository-name: DaniCatGames/jellyfin-openid-connect
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
